FROM docker.io/rust:1.64.0 as builder
WORKDIR /usr/src/holywar-telegram
ARG HOLYWAR_SOURCE_URL=https://github.com/ZaMaZaN4iK/holywar-telegram.git
ARG CACHE_DATE=2020-01-01
RUN git clone --single-branch --branch main ${HOLYWAR_SOURCE_URL}
WORKDIR holywar-telegram
RUN cargo install --path .

FROM docker.io/debian:bullseye-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/holywar-telegram /usr/local/bin/holywar-telegram
CMD ["holywar-telegram"]
