FROM rust:1.49.0 as builder
WORKDIR /usr/src/holywar-telegram
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/holywar-telegram /usr/local/bin/holywar-telegram
CMD ["holywar-telegram"]
